/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Controlador.Controlador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
/**
 *
 * @author Admin
 */
public class Vista extends javax.swing.JFrame {
    private Controlador controlador;  // Conexión con el controlador

    public Vista() {
        initComponents();
        controlador = new Controlador(this);  // Inicializa el controlador con la vista
        addListeners();  // Añadir los listeners para los botones y acciones
    }

    private void addListeners() {
        // Panel Registro
        btnRegistrar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                controlador.registrarVehiculo();  // Registra un vehículo
            }
        });

        btnMostrar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                controlador.mostrarVehiculos();  // Muestra todos los vehículos
            }
        });

        // Panel Motocicletas
        btnConsultar1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                controlador.consultarMotocicleta();  // Consulta motocicletas
            }
        });

        btnRealizar1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                controlador.realizarMantenimientoMotocicleta();  // Realiza mantenimiento a motocicletas
            }
        });

        // Panel Camiones
        btnConsultar2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                controlador.consultarCamion();  // Consulta camiones
            }
        });

        btnRealizar2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                controlador.realizarMantenimientoCamion();  // Realiza mantenimiento a camiones
            }
        });

        // Panel Coches
        btnConsultar3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                controlador.consultarCoche();  // Consulta coches
            }
        });

        btnRealizar3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                controlador.realizarMantenimientoCoche();  // Realiza mantenimiento a coches
            }
        });
    }


    // Métodos para obtener los datos de los campos de texto
    // Panel Registro
    public String getMatricula() {
        return txtMatricula.getText();
    }

    public String getMarca() {
        return txtMarca.getText();
    }

    public String getModelo() {
        return txtModelo.getText();
    }

    public int getAñoFabricacion() {
        try {
            return Integer.parseInt(txtMatricula.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Año de fabricación inválido.");
            return 0;
        }
    }

    public String getTurbo() {
        return txtTurbo.getText();
    }

    public String getTipoVehiculo() {
        return (String) boxTipovehiculo.getSelectedItem();  // Obtener el tipo seleccionado
    }

    // Panel Motocicletas
    public String getMatriculaMoto() {
        return txtMatriculaMoto.getText();
    }

    public int getCilindrada() {
        try {
            return Integer.parseInt(txtCilindrada.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cilindrada inválida.");
            return 0;
        }
    }

    // Panel Camiones
    public String getMatriculaCamion() {
        return txtMatriculaCamion.getText();
    }

    public double getPeso() {
        try {
            return Double.parseDouble(txtPeso.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Peso inválido.");
            return 0;
        }
    }

    // Panel Coches
    public String getMatriculaCoche() {
        return txtMatriculaCoche.getText();
    }

    // Método para mostrar los resultados en el área de texto de cada panel
    public void mostrarResultado(String resultado, JTextArea textArea) {
        textArea.setText(resultado);
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegistro = new javax.swing.JPanel();
        lblCoche = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAregistrar = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmatricula = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        boxTipovehiculo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtTurbo = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        jPanelMotocicletas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblCilindrada = new javax.swing.JLabel();
        btnConsultar1 = new javax.swing.JButton();
        txtCilindrada = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtResulMoto = new javax.swing.JTextArea();
        lblMatriculaMoto = new javax.swing.JLabel();
        txtMatriculaMoto = new javax.swing.JTextField();
        btnRealizar1 = new javax.swing.JButton();
        jPanelCamiones = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        btnConsultar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResulCamion = new javax.swing.JTextArea();
        txtPeso = new javax.swing.JTextField();
        lblMatriculaCamion = new javax.swing.JLabel();
        txtMatriculaCamion = new javax.swing.JTextField();
        btnRealizar2 = new javax.swing.JButton();
        jPanelCoches = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResulCoche = new javax.swing.JTextArea();
        btnConsultar3 = new javax.swing.JButton();
        lblMatriculaCoche = new javax.swing.JLabel();
        txtMatriculaCoche = new javax.swing.JTextField();
        btnRealizar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelRegistro.setBackground(new java.awt.Color(204, 204, 204));
        jPanelRegistro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCoche.setText("Gestión Vehiculo");

        lblNombre1.setText("Matricula:");

        jLabel1.setText("Marca:");

        jLabel2.setText("Modelo:");

        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtAregistrar.setColumns(20);
        txtAregistrar.setRows(5);
        jScrollPane1.setViewportView(txtAregistrar);

        jLabel4.setText("Turbo:");

        jLabel5.setText("Año Fabricación:");

        boxTipovehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camión", "Motocicleta", "Coche" }));
        boxTipovehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipovehiculoActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo Vehiculo:");

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistroLayout = new javax.swing.GroupLayout(jPanelRegistro);
        jPanelRegistro.setLayout(jPanelRegistroLayout);
        jPanelRegistroLayout.setHorizontalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addComponent(lblCoche)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre1)
                            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))))
                        .addGap(42, 42, 42)
                        .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTurbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxTipovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnMostrar)
                                .addGap(72, 72, 72))))
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelRegistroLayout.setVerticalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addComponent(lblCoche)
                        .addGap(30, 30, 30)
                        .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre1)
                            .addComponent(jLabel4)
                            .addComponent(txtTurbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(boxTipovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(btnMostrar))))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanelMotocicletas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Motocicleta");

        lblCilindrada.setText("Cilindrada:");

        btnConsultar1.setText("Consultar");
        btnConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar1ActionPerformed(evt);
            }
        });

        txtResulMoto.setColumns(20);
        txtResulMoto.setRows(5);
        jScrollPane4.setViewportView(txtResulMoto);

        lblMatriculaMoto.setText("Matricula Moto:");

        btnRealizar1.setText("Realizar");
        btnRealizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMotocicletasLayout = new javax.swing.GroupLayout(jPanelMotocicletas);
        jPanelMotocicletas.setLayout(jPanelMotocicletasLayout);
        jPanelMotocicletasLayout.setHorizontalGroup(
            jPanelMotocicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotocicletasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMotocicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMotocicletasLayout.createSequentialGroup()
                        .addComponent(lblCilindrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMotocicletasLayout.createSequentialGroup()
                        .addComponent(lblMatriculaMoto)
                        .addGap(18, 18, 18)
                        .addComponent(txtMatriculaMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMotocicletasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRealizar1)
                .addGap(2, 2, 2))
        );
        jPanelMotocicletasLayout.setVerticalGroup(
            jPanelMotocicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotocicletasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMotocicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelMotocicletasLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelMotocicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMatriculaMoto)
                            .addComponent(txtMatriculaMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelMotocicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCilindrada)
                            .addComponent(txtCilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMotocicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar1)
                    .addComponent(btnRealizar1))
                .addContainerGap())
        );

        jPanelCamiones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Camión");

        lblPeso.setText("Peso:");

        btnConsultar2.setText("Consultar");
        btnConsultar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar2ActionPerformed(evt);
            }
        });

        txtResulCamion.setColumns(20);
        txtResulCamion.setRows(5);
        jScrollPane2.setViewportView(txtResulCamion);

        lblMatriculaCamion.setText("Matricula Camion:");

        btnRealizar2.setText("Realizar");
        btnRealizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCamionesLayout = new javax.swing.GroupLayout(jPanelCamiones);
        jPanelCamiones.setLayout(jPanelCamionesLayout);
        jPanelCamionesLayout.setHorizontalGroup(
            jPanelCamionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCamionesLayout.createSequentialGroup()
                .addGroup(jPanelCamionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCamionesLayout.createSequentialGroup()
                        .addGroup(jPanelCamionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCamionesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelCamionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanelCamionesLayout.createSequentialGroup()
                                        .addComponent(lblPeso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelCamionesLayout.createSequentialGroup()
                                .addComponent(lblMatriculaCamion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMatriculaCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCamionesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar2)
                        .addGap(18, 18, 18)
                        .addComponent(btnRealizar2)))
                .addContainerGap())
        );
        jPanelCamionesLayout.setVerticalGroup(
            jPanelCamionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCamionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCamionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCamionesLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(13, 13, 13)
                        .addGroup(jPanelCamionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMatriculaCamion)
                            .addComponent(txtMatriculaCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCamionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPeso)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCamionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar2)
                    .addComponent(btnRealizar2))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanelCoches.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Coche");

        txtResulCoche.setColumns(20);
        txtResulCoche.setRows(5);
        jScrollPane3.setViewportView(txtResulCoche);

        btnConsultar3.setText("Consultar");
        btnConsultar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar3ActionPerformed(evt);
            }
        });

        lblMatriculaCoche.setText("Matricula Coche:");

        btnRealizar3.setText("Realizar");
        btnRealizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCochesLayout = new javax.swing.GroupLayout(jPanelCoches);
        jPanelCoches.setLayout(jPanelCochesLayout);
        jPanelCochesLayout.setHorizontalGroup(
            jPanelCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCochesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(jPanelCochesLayout.createSequentialGroup()
                        .addComponent(lblMatriculaCoche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMatriculaCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCochesLayout.createSequentialGroup()
                        .addComponent(btnConsultar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRealizar3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCochesLayout.setVerticalGroup(
            jPanelCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCochesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanelCochesLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMatriculaCoche)
                            .addComponent(txtMatriculaCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultar3)
                            .addComponent(btnRealizar3))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jPanelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanelMotocicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCamiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelCoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelMotocicletas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCamiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxTipovehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipovehiculoActionPerformed
         String tipoVehiculo = (String) boxTipovehiculo.getSelectedItem();

    if (tipoVehiculo.equals("Camion")) {
        txtPeso.setEnabled(true);  // Habilitar campo para el peso de camión
        txtCilindrada.setEnabled(false);  // Deshabilitar campo de cilindrada
    } else if (tipoVehiculo.equals("Motocicleta")) {
        txtPeso.setEnabled(false);  // Deshabilitar campo de peso
        txtCilindrada.setEnabled(true);  // Habilitar campo de cilindrada
    } else {
        txtPeso.setEnabled(false);
        txtCilindrada.setEnabled(false);
    }
    }//GEN-LAST:event_boxTipovehiculoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        controlador.registrarVehiculo();  // Llama al método del controlador para registrar un vehículo
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar1ActionPerformed
        controlador.consultarMotocicleta();  // Llama al método del controlador para consultar motocicletas
    }//GEN-LAST:event_btnConsultar1ActionPerformed

    private void btnRealizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizar1ActionPerformed
        controlador.realizarMantenimientoMotocicleta();  // Llama al método del controlador para realizar mantenimiento a motocicletas
    }//GEN-LAST:event_btnRealizar1ActionPerformed

    private void btnConsultar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar2ActionPerformed
       controlador.consultarCamion();  // Llama al método del controlador para consultar camiones
    }//GEN-LAST:event_btnConsultar2ActionPerformed

    private void btnConsultar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar3ActionPerformed
        controlador.consultarCoche();  // Llama al método del controlador para consultar coches
    }//GEN-LAST:event_btnConsultar3ActionPerformed

    private void btnRealizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizar2ActionPerformed
        controlador.realizarMantenimientoCoche();  // Llama al método del controlador para realizar mantenimiento a coches
    }//GEN-LAST:event_btnRealizar2ActionPerformed

    private void btnRealizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizar3ActionPerformed
        controlador.realizarMantenimientoCamion();  // Llama al método del controlador para realizar mantenimiento a camiones
    }//GEN-LAST:event_btnRealizar3ActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // Obtener el resultado más reciente desde el controlador y mostrarlo en el área de texto
    String resultado = controlador.obtenerResultado();  
    txtAregistrar.setText(resultado);  // Mostrar el resultado en el área de texto de registro
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxTipovehiculo;
    private javax.swing.JButton btnConsultar1;
    private javax.swing.JButton btnConsultar2;
    private javax.swing.JButton btnConsultar3;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRealizar1;
    private javax.swing.JButton btnRealizar2;
    private javax.swing.JButton btnRealizar3;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelCamiones;
    private javax.swing.JPanel jPanelCoches;
    private javax.swing.JPanel jPanelMotocicletas;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCilindrada;
    private javax.swing.JLabel lblCoche;
    private javax.swing.JLabel lblMatriculaCamion;
    private javax.swing.JLabel lblMatriculaCoche;
    private javax.swing.JLabel lblMatriculaMoto;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPeso;
    public javax.swing.JTextArea txtAregistrar;
    private javax.swing.JTextField txtCilindrada;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMatriculaCamion;
    private javax.swing.JTextField txtMatriculaCoche;
    private javax.swing.JTextField txtMatriculaMoto;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPeso;
    public javax.swing.JTextArea txtResulCamion;
    public javax.swing.JTextArea txtResulCoche;
    public javax.swing.JTextArea txtResulMoto;
    private javax.swing.JTextField txtTurbo;
    private javax.swing.JTextField txtmatricula;
    // End of variables declaration//GEN-END:variables

}